### ISSUE TITLE
Pour cuisine le frigo

### ISSUE THREAD

**Issue by Jat15** [turbogus/deco#4]
Il faudrait un icône 16x16 pour représenté le frigo.

**Comment by turbogus** [comment]
ok, le seul soucis vient de l'inscription "SMEG", difficile à mettre dans un cube de 16x16. Perso, j'ai essayé mais pas reussi

**Comment by Jat15** [comment]
pas grave temps qu'on reconnais c'est le frigo. Et prend les meme dimension que tes autre texture.

**Comment by turbogus** [comment]
Si on change la texture, autant changer la couleur, rouge fait bobo les yeux ! ( gris metalisé ? )

**Comment by Jat15** [comment]
Je veux surtout une image du frigo pour le représenté en icône.

**Comment by turbogus** [comment]
je vois pour ça aujourd'hui
